# Generated by Django 5.2.1 on 2025-11-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_migrate_resolved_to_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.CharField(blank=True, help_text='เช่น 081-234-5678 หรือ @lineid', max_length=100, verbose_name='เบอร์โทรหรือ Line ID'),
        ),
    ]
