# Generated by Django 5.2.1 on 2026-01-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_ticketimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
