# Generated by Django 5.2.1 on 2026-01-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'เปิดงาน'), ('in_progress', 'กำลังดำเนินการ'), ('on_hold', 'พักงาน'), ('closed', 'เสร็จแล้ว')], default='open', max_length=20),
        ),
    ]
